### PR TITLE
Add rubocop files

### LINKED ISSUE #9: Needs new .rubocop files
ping @bdunne

Getting comments like https://github.com/ManageIQ/pg-pglogical/pull/8#issuecomment-281806948 from the bot.

### PR DESCRIPTION
**Pull request by bdunne**
Fixes #9

### CODE REVIEW

**Comment by bdunne** [comment]
@miq-bot assign @carbonin

**Comment by carbonin** [comment]
I'm not sure what's going on with codeclimate here ... @Fryguy ?

**Comment by jrafanie** [comment]
@carbonin @Fryguy looks like it blew up trying to get to `raw.githubusercontent.com`, can you close/open to kick it?

image

**Comment by carbonin** [comment]
Tried once already.

**Pull request merged**
